name: Deploy

on:
  push:
    paths:
      - 'fdroid/tmp-apks/*.apk'

jobs:
  linux:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup fdroidserver
        run: |
          sudo add-apt-repository ppa:fdroid/fdroidserver
          sudo apt update
          sudo apt install fdroidserver

      - name: Move apks
        run: |
          for i in fdroid/tmp-apks/*.apk; do mv $i fdroid/repo; done
          rm -r fdroid/tmp-apks

      - name: fdroid Update
        run: |
          cd fdroid
          fdroid update
          cd ..

      - name: Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Auto deploy'
          add_options: '--all'
          skip_checkout: true
          disable_globbing: true

      - name: Create Pull Request
        if: ${{ startsWith(github.ref_name, 'deploy') }}
        uses: devops-infra/action-pull-request@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: master
          title: 'Auto Deploy Pull Request'
          reviewer: 'txyyh'
